name: HerokuJavaGettingStarted

on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [11, 13, 17]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{matrix.java-version}}
        uses: actions/setup-java@v3
        with:
          java-version: ${{matrix.java-version}}
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - uses: actions/upload-artifact@v3
        with:
          name: my-project-builder
          path: ./target/*.jar